services:
  api:
    build:
      context: ./server/API
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env.production

  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env.production
    ports:
      - "3000:80"
