services:
  api:
    build:
      context: ./server/API
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    db:restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: src/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:80"
    restart: unless-stopped
